language: go

go:
  - 1.8.3
  - tip

services:
  - docker

install:
  - go get github.com/golang/snappy
  - go get git.apache.org/thrift.git/lib/go/thrift
  - go get github.com/colinmarc/hdfs

script:
  - make test

after_script:


after_success:
