language: go

go:
  - 1.8.3
  - tip

services:
  - docker

install:
  - go get github.com/golang/snappy
  - go get github.com/apache/thrift/lib/go/thrift
  - go get github.com/colinmarc/hdfs
  - go get github.com/spf13/afero

script:
  - make test

after_script:


after_success:
